packages:
- '.'
- location:
    git: https://github.com/isovector/SG.git
    commit: 222c4e42b4b8574182e24430bc1722faeb9ef508

resolver: lts-7.1
extra-deps:
    - sdl2-1.2.0
    - frpnow-0.18

flags: {}

extra-package-dbs: []
