packages:
- '.'
# - location:
#     git: https://github.com/isovector/SG.git
#     commit: fe733adab45bf6abb1a1a9457f398b96fe643e68

resolver: lts-9.0
extra-deps:
    - sdl2-2.3.0
    - frpnow-0.18

flags: {}

extra-package-dbs: []
