packages:
- '.'
- location:
    git: https://github.com/isovector/SG.git
    commit: f8427079ed6dbbd7b9dd3fd5fdecdf2d0087847a

resolver: lts-7.1
extra-deps:
    - sdl2-1.2.0
    - frpnow-0.18

flags: {}

extra-package-dbs: []
