packages:
- '.'
- location:
    git: https://github.com/isovector/SG.git
    commit: 22d733e62b085209979d4dc05d8e6e94d4cb1a8d

resolver: lts-5.2
extra-deps:
    - sdl2-1.2.0

flags: {}

extra-package-dbs: []
